# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10gAU0mggAYtBCb-TDyY3qAaW6K5-841s
"""

# Uninstall existing conflicting versions
!pip uninstall -y torch torchvision torchaudio

# Install compatible versions of PyTorch and torchvision (CUDA 11.8)
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# Install required libraries
!pip install diffusers transformers accelerate moviepy gtts google-colab

!pip install moviepy pydub numpy opencv-python gtts

import os
import torch
import shutil
import numpy as np
from PIL import Image
from gtts import gTTS
from moviepy.editor import *
from google.colab import files
import warnings

# Suppress moviepy warnings
warnings.filterwarnings("ignore", category=SyntaxWarning, module="moviepy")

from diffusers import StableDiffusionPipeline

# Load Stable Diffusion model with optimized settings
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
pipe.to("cuda")  # Move model to GPU
pipe.enable_attention_slicing()  # Optimize memory usage

print("✅ Stable Diffusion model loaded successfully!")

# Get user inputs
video_description = input("🎥 Enter the video description: ")
total_duration = float(input("⏳ Enter total video duration in seconds: "))
num_images = int(input("🖼️ Enter number of images to generate: "))

# Calculate image duration
image_duration = total_duration / num_images
print(f"✅ Each image will be displayed for {image_duration:.2f} seconds.")

# Create folder to save images
os.makedirs("images", exist_ok=True)

# Generate images
for i in range(num_images):
    print(f"🎨 Generating Image {i+1}/{num_images}...")
    image = pipe(video_description).images[0]  # Generate image
    img_path = f"images/image_{i+1}.png"
    image.save(img_path)
    print(f"✅ Image {i+1} saved at {img_path}")

# Convert description to speech
voiceover = gTTS(text=video_description, lang="en", slow=False)

# Save voiceover file
audio_path = "voiceover.mp3"
voiceover.save(audio_path)
print(f"✅ Voiceover saved as {audio_path}")

import os
import numpy as np
from pydub import AudioSegment
from moviepy.editor import (
    ImageSequenceClip, AudioFileClip, CompositeVideoClip, ImageClip
)
from PIL import Image, ImageDraw, ImageFont

# ✅ Load images (ENSURE NO BAKED-IN SUBTITLES)
image_files = [f"images/image_{i+1}.png" for i in range(num_images)]

# ✅ Get duration of each image
durations = [image_duration] * num_images

# ✅ Create video clip from images
video_clip = ImageSequenceClip(image_files, durations=durations)

# ✅ Load and set audio
audio_clip = AudioFileClip(audio_path).set_duration(total_duration)
video_clip = video_clip.set_audio(audio_clip)

# ✅ Ensure video does NOT extend past its duration
video_clip = video_clip.set_duration(total_duration)

# ✅ Function to generate subtitle timing based on audio
def get_speech_intervals(audio_path, text, total_duration):
    audio = AudioSegment.from_file(audio_path)
    audio_length = len(audio) / 1000  # Convert to seconds
    words = text.upper().split()  # ✅ Convert text to ALL CAPS

    # ✅ Calculate words per second dynamically
    words_per_second = len(words) / audio_length
    timestamps = [i / words_per_second for i in range(len(words))]

    # ✅ Distribute words based on timing
    subtitle_data = []
    current_text = ""
    last_time = 0
    for i, word in enumerate(words):
        current_text += word + " "
        if i % 4 == 0 or i == len(words) - 1:  # Group every 4 words per subtitle
            subtitle_data.append((last_time, timestamps[i], current_text.strip()))
            last_time = timestamps[i]
            current_text = ""

    return subtitle_data

# ✅ Generate properly timed subtitles
subtitles = get_speech_intervals(audio_path, video_description, total_duration)

# ✅ Function to find a valid BOLD font
def get_valid_font():
    possible_fonts = [
        "/usr/share/fonts/truetype/msttcorefonts/Impact.ttf",  # Impact (Linux)
        "/usr/share/fonts/truetype/msttcorefonts/Arial_Black.ttf",  # Arial Black (Linux)
        "C:\\Windows\\Fonts\\impact.ttf",  # Impact (Windows)
        "C:\\Windows\\Fonts\\arialbd.ttf",  # Arial Bold (Windows)
        "/System/Library/Fonts/Supplemental/Impact.ttf",  # Impact (Mac)
        "/System/Library/Fonts/Supplemental/Arial Black.ttf",  # Arial Black (Mac)
    ]
    for font in possible_fonts:
        if os.path.exists(font):
            return font
    return None  # If no system font is found

# ✅ Function to generate MASSIVE subtitle overlay clips (REAL BOLD TEXT)
def create_subtitle_clips(subtitles, video_clip):
    subtitle_clips = []
    font_path = get_valid_font()

    if font_path is None:
        print("⚠️ No system font found. Using default PIL font.")
        font = ImageFont.load_default()
    else:
        font = ImageFont.truetype(font_path, 180)  # ✅ HUGE REAL BOLD FONT

    for start, end, text in subtitles:
        if end > total_duration:  # ✅ Ensure subtitle doesn't extend video length
            end = total_duration

        # ✅ Create transparent subtitle image
        subtitle_img = Image.new("RGBA", (video_clip.w, 300), (0, 0, 0, 0))
        draw = ImageDraw.Draw(subtitle_img)

        # ✅ Get text size for perfect centering
        text_bbox = draw.textbbox((0, 0), text, font=font)
        text_width, text_height = text_bbox[2] - text_bbox[0], text_bbox[3] - text_bbox[1]
        text_x = (video_clip.w - text_width) // 2
        text_y = 80  # Adjust subtitle position

        # ✅ BIG, BOLD, PURE YELLOW TEXT (No fake thickness)
        draw.text((text_x, text_y), text, font=font, fill="yellow")

        # ✅ Convert to moviepy clip
        subtitle_clip = (
            ImageClip(np.array(subtitle_img), duration=(end - start))
            .set_start(start)
            .set_position(("center", "bottom"))
        )
        subtitle_clips.append(subtitle_clip)

    return subtitle_clips

# ✅ Generate overlay subtitles
subtitle_overlays = create_subtitle_clips(subtitles, video_clip)

# ✅ Combine video with subtitles
final_video = CompositeVideoClip([video_clip] + subtitle_overlays)

# ✅ Ensure final video stops at correct duration
final_video = final_video.set_duration(total_duration)

# ✅ Export final video
video_path = "final_video.mp4"
final_video.write_videofile(video_path, codec="libx264", fps=1)

print(f"🎥 Video saved as {video_path}")

# Download the video
files.download(video_path)
print("🎉 Video is ready for download!")

